# Sample pipeline for testing FreeBSD Azure Pipelines agent

trigger:
- master

pool:
  name: 'SelfHosted'
  demands:
  - Agent.OS -equals FreeBSD

variables:
  buildConfiguration: 'Release'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

